# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHomePage():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_homePage(self):
    # Test name: HomePage
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 1364x766 | 
    self.driver.set_window_size(1364, 766)
    # 3 | click | id=hero-title__text--bottom | 
    self.driver.find_element(By.ID, "hero-title__text--bottom").click()
    # 4 | click | css=.next > .flickity-button-icon | 
    self.driver.find_element(By.CSS_SELECTOR, ".next > .flickity-button-icon").click()
    # 5 | click | css=.previous | 
    self.driver.find_element(By.CSS_SELECTOR, ".previous").click()
    # 6 | click | id=hero-grid | 
    self.driver.find_element(By.ID, "hero-grid").click()
    # 7 | click | css=#hero-weather__symbol > img | 
    self.driver.find_element(By.CSS_SELECTOR, "#hero-weather__symbol > img").click()
    # 8 | click | css=.menu-button__bar--bottom | 
    self.driver.find_element(By.CSS_SELECTOR, ".menu-button__bar--bottom").click()
    # 9 | click | css=.s-m__trigger > .menu-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".s-m__trigger > .menu-button").click()
    # 10 | click | css=a > .float-right | 
    self.driver.find_element(By.CSS_SELECTOR, "a > .float-right").click()
  
