# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestThemes():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_themes(self):
    # Test name: Themes
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 1364x766 | 
    self.driver.set_window_size(1364, 766)
    # 3 | click | linkText=THEMES | 
    self.driver.find_element(By.LINK_TEXT, "THEMES").click()
    # 4 | click | css=.subnav__icon-nav:nth-child(1) h2 | 
    self.driver.find_element(By.CSS_SELECTOR, ".subnav__icon-nav:nth-child(1) h2").click()
    # 5 | click | css=.subnav__icon-nav:nth-child(3) h2 | 
    self.driver.find_element(By.CSS_SELECTOR, ".subnav__icon-nav:nth-child(3) h2").click()
    # 6 | click | css=.subnav__icon-nav:nth-child(4) use | 
    self.driver.find_element(By.CSS_SELECTOR, ".subnav__icon-nav:nth-child(4) use").click()
    # 7 | click | css=.subnav__icon-nav:nth-child(5) use | 
    self.driver.find_element(By.CSS_SELECTOR, ".subnav__icon-nav:nth-child(5) use").click()
  
